version: "3.9"

services:
  mindful:
    container_name: mindful
    build: .
    image: mindful
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
  db:
    container_name: db
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  pgdata:

