version: "3.4"

services:
  mindful:
    container_name: mindful
    build: .
    image: mindful
    restart: always
    depends_on:
      - mindful-db
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@mindful-db:5432/postgres
    networks:
      - mindful_network
  mindful-db:
    container_name: mindful-db
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - mindful_network
volumes:
  pgdata:

networks:
        mindful_network:
